package stack

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

type resolvConfStack struct{}

func (s *resolvConfStack) Type() StackType {
	return StackResolvConf
}

func (s *resolvConfStack) Detect() bool {
	// Only match if resolvectl AND nmcli are both unavailable
	if _, err := exec.LookPath("resolvectl"); err == nil {
		return false
	}
	if _, err := exec.LookPath("nmcli"); err == nil {
		return false
	}
	_, err := os.Stat("/etc/resolv.conf")
	return err == nil
}

func (s *resolvConfStack) resolvePath() (string, error) {
	return resolveResolvconfPath("/etc")
}

func resolveResolvconfPath(baseDir string) (string, error) {
	resolvPath := filepath.Join(baseDir, "resolv.conf")
	target, err := os.Readlink(resolvPath)
	if err != nil {
		// Not a symlink
		return resolvPath, nil
	}
	if !strings.HasPrefix(target, "/") {
		target = filepath.Join(baseDir, target)
	}
	// If it points to systemd-resolved or NM managed file, we shouldn't be here
	if strings.Contains(target, "/run/systemd/resolve") || strings.Contains(target, "/run/NetworkManager") {
		return resolvPath, nil
	}
	return target, nil
}

func (s *resolvConfStack) CurrentDNS() (string, error) {
	target, err := s.resolvePath()
	if err != nil {
		return "", err
	}
	data, err := os.ReadFile(target)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

func (s *resolvConfStack) SetDNS(primary, secondary string) error {
	target, err := s.resolvePath()
	if err != nil {
		return err
	}

	var sb strings.Builder
	sb.WriteString("# Generated by dncensor\n")
	sb.WriteString(fmt.Sprintf("nameserver %s\n", primary))
	if secondary != "" {
		sb.WriteString(fmt.Sprintf("nameserver %s\n", secondary))
	}

	// Preserve search/domain lines from current
	if current, err := os.ReadFile(target); err == nil {
		for _, line := range strings.Split(string(current), "\n") {
			if strings.HasPrefix(line, "search ") || strings.HasPrefix(line, "domain ") {
				sb.WriteString(line + "\n")
			}
		}
	}

	// Atomic write via temp file + rename
	tmp, err := os.CreateTemp(filepath.Dir(target), ".resolv.conf.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	if _, err := tmp.WriteString(sb.String()); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return fmt.Errorf("write temp: %w", err)
	}
	tmp.Close()

	if err := os.Rename(tmp.Name(), target); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("rename %s -> %s: %w", tmp.Name(), target, err)
	}

	return nil
}

func (s *resolvConfStack) SetDOH(endpoint string) error {
	return fmt.Errorf("/etc/resolv.conf does not support DoH")
}

func (s *resolvConfStack) CaptureDNS() ([]byte, error) {
	target, err := s.resolvePath()
	if err != nil {
		return nil, err
	}

	data, err := os.ReadFile(target)
	if err != nil {
		return nil, err
	}

	return data, nil
}

func (s *resolvConfStack) ApplyDNS(content []byte) error {
	target, err := s.resolvePath()
	if err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(target), ".resolv.conf.*")
	if err != nil {
		return fmt.Errorf("create temp: %w", err)
	}
	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		os.Remove(tmp.Name())
		return fmt.Errorf("write temp: %w", err)
	}
	tmp.Close()

	if err := os.Rename(tmp.Name(), target); err != nil {
		os.Remove(tmp.Name())
		return fmt.Errorf("rename %s -> %s: %w", tmp.Name(), target, err)
	}

	return nil
}

func (s *resolvConfStack) RequiresRoot() bool {
	return true
}
